from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

import pdfplumber
import pypdf
import reportlab
from pypdf import PdfReader, PdfWriter
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def env() -> int:
    print(json.dumps({"python": sys.executable, "pypdf": getattr(pypdf, "__version__", None), "pdfplumber": getattr(pdfplumber, "__version__", None), "reportlab": getattr(reportlab, "Version", None)}, ensure_ascii=False, indent=2))
    return 0


def _build_story(lines: list[str]):
    pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    body.fontName = "STSong-Light"
    story = []
    for line in lines:
        story.append(Paragraph(line if line.strip() else " ", body))
        story.append(Spacer(1, 10))
    return story


def create_from_text(input_path: Path, output_path: Path) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    SimpleDocTemplate(str(output_path), pagesize=A4).build(_build_story(input_path.read_text(encoding="utf-8").splitlines()))
    print(output_path)
    return 0


def create_from_json(input_path: Path, output_path: Path) -> int:
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    lines = [payload.get("project_name", "Project Brief"), f"Owner: {payload.get('owner', '')}", f"Deadline: {payload.get('deadline', '')}", "Objectives:"]
    lines.extend(f"- {item}" for item in payload.get("objectives", []))
    lines.append("Risks:")
    lines.extend(f"- {item}" for item in payload.get("risks", []))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    SimpleDocTemplate(str(output_path), pagesize=A4).build(_build_story(lines))
    print(output_path)
    return 0


def merge(output_path: Path, input_paths: list[Path]) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    writer = PdfWriter()
    for input_path in input_paths:
        reader = PdfReader(str(input_path))
        for page in reader.pages:
            writer.add_page(page)
    with output_path.open("wb") as fh:
        writer.write(fh)
    print(output_path)
    return 0


def split(input_path: Path, output_dir: Path) -> int:
    output_dir.mkdir(parents=True, exist_ok=True)
    reader = PdfReader(str(input_path))
    written = []
    for index, page in enumerate(reader.pages, start=1):
        writer = PdfWriter()
        writer.add_page(page)
        output_path = output_dir / f"page_{index:03d}.pdf"
        with output_path.open("wb") as fh:
            writer.write(fh)
        written.append(str(output_path))
    print(json.dumps(written, ensure_ascii=False, indent=2))
    return 0


def _create_lines_pdf(lines: list[str], output_path: Path) -> None:
    SimpleDocTemplate(str(output_path), pagesize=A4).build(_build_story(lines))


def modify_with_cover(input_path: Path, output_path: Path) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp_dir:
        cover_path = Path(tmp_dir) / "cover.pdf"
        _create_lines_pdf(["Updated Packet", "Generated by kimi-pdf WSL skill"], cover_path)
        merge(output_path, [cover_path, input_path])
    return 0


def validate(path: Path) -> int:
    reader = PdfReader(str(path))
    first_page_text = reader.pages[0].extract_text() or ""
    print(json.dumps({"pages": len(reader.pages), "first_page_preview": first_page_text[:120]}, ensure_ascii=False, indent=2))
    return 0


def extract_text(path: Path) -> int:
    texts = []
    with pdfplumber.open(str(path)) as pdf:
        for page in pdf.pages:
            texts.append(page.extract_text() or "")
    print("\n".join(texts))
    return 0


def main() -> int:
    if len(sys.argv) < 2:
        return 1
    command = sys.argv[1]
    if command == "env":
        return env()
    if command == "create-from-text":
        return create_from_text(Path(sys.argv[2]), Path(sys.argv[3]))
    if command == "create-from-json":
        return create_from_json(Path(sys.argv[2]), Path(sys.argv[3]))
    if command == "modify-with-cover":
        return modify_with_cover(Path(sys.argv[2]), Path(sys.argv[3]))
    if command == "merge":
        return merge(Path(sys.argv[2]), [Path(arg) for arg in sys.argv[3:]])
    if command == "split":
        return split(Path(sys.argv[2]), Path(sys.argv[3]))
    if command == "validate":
        return validate(Path(sys.argv[2]))
    if command == "extract-text":
        return extract_text(Path(sys.argv[2]))
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
